### PR TITLE
feat: array assert support by key and value

### PR DESCRIPTION
**Pull request by ivan-velasco**
- As the order of arrays in responses may vary, a new assertion has been introduced to perform lookups based on key and value.

**Example:**
```yml
- steps:
  - type: exec
    script: echo '[{"foo":"bar"}, {"foo2":"bar2"}, {"foo2":"bar3" }]'
    assertions:
      - result.systemoutjson ShouldContainKeyValue foo2 bar2
```

### CODE REVIEW

**Comment by aditi-malik** [comment]
> * As the order of arrays in responses may vary, a new assertion has been introduced to perform lookups based on key and value.
> 
> **Example:**
> 
> ```yaml
> - steps:
>   - type: exec
>     script: echo '[{"foo":"bar"}, {"foo2":"bar2"}, {"foo2":"bar3" }]'
>     assertions:
>       - result.systemoutjson ShouldContainKeyValue foo2 bar2
> ```

This is a pretty helpful feature for our tests. Thanks @ivan-velasco for working on it.

**Comment by yesnault** [comment]
Thank you @ivan-velasco  for this proposal. Are you ok with https://github.com/ovh/venom/pull/747/files ?

**Comment by ivan-velasco** [comment]
@yesnault yes this works for more scenarios ☑️

**Comment by yesnault** [comment]
#747 merged.

**Pull request closed without merging**
