### PR TITLE
chore: bump go.mod

### PR DESCRIPTION
**Pull request by yesnault**
close #726
close #725

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#122.0 ✘  
* Build
  * Build ✘  
  * Unit Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#124.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#126.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#153.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Review by richardlt — APPROVED** [review]

**Review by fsamin — APPROVED** [review]

**Pull request merged**
