### PR TITLE
fix: multilines in args user executor

### LINKED ISSUE #392: Multiline arg for custom executor
Hi,
I'm trying to create a custom executor following https://github.com/ovh/venom#user-defined-executors but multiline args don't seem to work :( 

Example with this custom executor:

```yml
executor: perl
input:
  script: 3
steps:
- type: exec
  script: |
    #!/usr/bin/perl
    use 5.010;
    use strict;
    use warnings;

    use JSON;

    my $json = {
      a => "{{.input.script}}"
    };

    print encode_json $json;
  assertions:
  - result.code ShouldEqual 0
output:
  all: '{{.result.systemoutjson}}'
```

The following test works:

```yml
name: testsuite with a user executor
testcases:
- name: testA
  steps:
  - type: perl
    script: 4
    assertions:
    - result.alljson.a ShouldEqual 4
```

> venom run test.yml
> • testsuite with a user executor (test.yml)
>        • testA SUCCESS

but if I replace the script with a multiline yml string it fails:

```yml
name: testsuite with a user executor
testcases:
- name: testA
  steps:
  - type: perl
    script: |
      4
    assertions:
    - result.alljson.a ShouldEqual 4
```

> venom run test.yml
> • testsuite with a user executor (test.yml)
>        • testA FAILURE
>Testcase "testA", step #0: Assertion "result.alljson.a ShouldEqual 4" failed. expected: 4  got: 3 (test.yml:9)

### PR DESCRIPTION
**Pull request by yesnault**
close #392

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#921.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#921.2 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#921.3 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#921.4 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Review by fsamin — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#930.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#932.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Pull request merged**
