### PR TITLE
chore: enable git pod

### PR DESCRIPTION
**Pull request by fsamin**
Signed-off-by: francois  samin <francois.samin@corp.ovh.com>

### CODE REVIEW

**Review by yesnault — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#895.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#900.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Review by yesnault — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#906.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#906.1 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by fsamin** [comment]
Hi @scraly , i finally managed to run properly all our stuff from venom in GitPod.
Now we are sure that anyone can contribute and is able to run all the tests \o/

I have to admit that I am impressed by this tool !

**Pull request merged**
