### PR TITLE
feat: preserve case

### LINKED ISSUE #522: Variables in skip statements are not case sensitive
The variable case in skip assertions are not managed.
We must currently use the variable lowercase version to make it works.

Example:
```yaml
name: "Skip testsuite"
vars:
  Foo: true

testcases:
- name: dont-skip-this
  skip:
  - Foo ShouldBeTrue
  steps:
  - type: exec
    script: exit 0

- name: skip-this
  skip: 
    - foo ShouldBeTrue
  steps:
  - type: exec
    script: exit 0
```

```
 • Skip testsuite (test_skip.yml)
 	• dont-skip-this SKIPPED
 	• skip-this SUCCESS
```

### PR DESCRIPTION
**Pull request by yesnault**
It's now possible to read something like that :
```json
{
  "foo": "bar",
  "FOO": "truc",
}
```
and use these variables:

```yml
- type: readfile
    path: the_file.json
    info: "{{.Result.ContentJSON.foo}}-{{.Result.ContentJSON.FOO}}"
```

Environment variable: VENOM_PRESERVE_CASE

venom 1.1.x
  VENOM_PRESERVE_CASE="AUTO" is equals to VENOM_PRESERVE_CASE="OFF"

venom 1.2.x
  VENOM_PRESERVE_CASE="AUTO" is equals to VENOM_PRESERVE_CASE="ON"

venom 1.1 users, you can try:

```sh
> export VENOM_PRESERVE_CASE="ON";
> venom run ...
```

close #522
close #547
close #522

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

### CODE REVIEW

**Review by fsamin — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#946.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#948.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#949.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#952.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✔ 
* Package-Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Stage 4
  * Buildinfo ✘

**Pull request merged**
