### PR TITLE
refactor: move cli to cmd package

### PR DESCRIPTION
**Pull request by yesnault**
and refactor Makefile

make help
make build with cross compilation
make tests with coverage and test-results as junit

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-venom#343.0 ✘  
* Build
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom#344.0 ✘  
* Build
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom#345.0 ✘  
* Build
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom#346.0 ✘  
* Build
  * Build ✘

**Review by fsamin — APPROVED** [review]

**Pull request merged**
