### PR TITLE
fix: interpolate arg var only once

### LINKED ISSUE #445: bug: value of a variable generated through an helper is not consistent
If I use a helper `randAlpha` to initialize a variable in a dedicated file (used with `--var-from-file` option), value of my variable is not consistent across the testsuite.

### Steps to reproduce

```console
# cat > e.yml << EOF
---
name: e
version: 2
testcases:
- name: myvar_first
  steps:
  - type: exec
    script: "echo myvar first time: {{.myvar}}"
    info: "{{.result.systemout}}"

- name: myvar_second
  steps:
  - type: exec
    script: "echo myvar second time: {{.myvar}}"
    info: "{{.result.systemout}}"
EOF

# cat > vars.yml <<EOF
---
myvar: '{{ randAlpha 3 }}'
EOF

```
### Actual results

```console
# venom run e.yml --var-from-file vars.yml 
 • e (e.yml)
 	• myvar_first SUCCESS
	  [info] myvar first time: CBq (e.yml:8) (e.yml:8)
 	• myvar_second SUCCESS
	  [info] myvar second time: cjB (e.yml:14) (e.yml:14)
```

### Expected results
I expect `myvar` to have the same value from beginning to end of test suite.

If variable declaration is done at beginning of testsuite like this:

```console
# cat > e.yml << EOF
---
name: e
vars:
  myvar: '{{ randAlpha 3 }}'
version: 2
testcases:
- name: myvar_first
  steps:
  - type: exec
    script: "echo myvar first time: {{.myvar}}"
    info: "{{.result.systemout}}"

- name: myvar_second
  steps:
  - type: exec
    script: "echo myvar second time: {{.myvar}}"
    info: "{{.result.systemout}}"
EOF
```

Value of `myvar` is consistent from beginning to end of test suite.

I also noticed some weird behaviors if I initialize another variable with value of this variable like: `myvar2: '{{.myvar}}'`

### PR DESCRIPTION
**Pull request by yesnault**
close #445

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#915.1 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#923.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#923.1 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#923.2 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Review by fsamin — APPROVED** [review]

**Pull request merged**
