### PR TITLE
fix(cli): give higher priority to --var over --var-from-file

### PR DESCRIPTION
**Pull request by reno-xjb**
#245

### CODE REVIEW

**Comment by nqb** [comment]
Hello @fsamin,

Did you see [my comment](https://github.com/ovh/venom/issues/245#issuecomment-607199108) on related issue ?

**Comment by yesnault** [comment]
I'm ok with this PR too, var-from-file have to be overrided by var flag, without an option to choose precedence.

**Comment by nqb** [comment]
> I'm ok with this PR too, var-from-file have to be overrided by var flag, without an option to choose precedence.

Would be nice to mention this in the help of `venom run`

**Comment by yesnault** [comment]
> > I'm ok with this PR too, var-from-file have to be overrided by var flag, without an option to choose precedence.
> 
> Would be nice to mention this in the help of `venom run`

done: https://github.com/ovh/venom/commit/a5ad48bb87e876dd268f896df40064c0f4a10f00

**Pull request merged**
