### PR TITLE
feat: allow specifying extra body supported content type

### PR DESCRIPTION
**Pull request by guoweis-outreach**
I need to parse the type `application/vnd.apple.mpegurl` which is a text file, i.e. m3u8. 

If this looks ok, i'll provide test and documentation.

### CODE REVIEW

**Review by yesnault — CHANGES_REQUESTED** [review]
Hi @guoweis-outreach, seems good, thank you for this PR.

Can you add documentation on http/README.md file, and  unit test and/or tests into tests/ directory about that please?

Thank you

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#1111.1 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#1111.2 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#21.0 ■   
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ■

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#21.0 ■   
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ■

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#21.1 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✔ 
* Package-Analyze
  * Docker ✘  
  * Sonar ✔

**Comment by yesnault** [comment]
> Hi @guoweis-outreach, seems good, thank you for this PR.
> 
> Can you add documentation on http/README.md file, and unit test and/or tests into tests/ directory about that please?
> 
> Thank you

@guoweis-outreach  Feel free to reopen this PR with README / test updated.

**Pull request closed without merging**
