### PR TITLE
feat: plugins support

### PR DESCRIPTION
**Pull request by yesnault**
plugin odbc
plugin hello

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-venom#360.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom#361.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Review by fsamin — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build-venom#363.0 ■   
* Build
  * Build ■

**Comment by ovh-cds** [comment]
CDS Report build-venom#363.0 ■   
* Build
  * Build ■

**Comment by ovh-cds** [comment]
CDS Report build-venom#363.1 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom#364.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Pull request merged**
