### PR TITLE
feat: official docker image

### LINKED ISSUE #557: Publish docker image to docker hub
Hi,
In your manual, you propose to build docker image.
```
git clone git@github.com:ovh/venom.git
$ cd venom
$ docker run -it $(docker build -q .) --rm -v $(pwd)/outputs:/outputs -v $(pwd):/tests run /tests/testsuite.yaml
```

Instead, I would like to get pre-built docker image and use it with my `yaml` files.
What do you think about publishing docker image to docker hub?
Manual: https://docs.docker.com/ci-cd/github-actions/

### PR DESCRIPTION
**Pull request by fsamin**
close #557 , #433

Signed-off-by: francois  samin <francois.samin@corp.ovh.com>

### CODE REVIEW

**Review by yesnault — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#934.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#934.1 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#935.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#936.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests -   
* Package-Analyze
  * Docker ✘  
  * Sonar ✔

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#936.1 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests -   
* Package-Analyze
  * Docker ✘  
  * Sonar ✔

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#936.2 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests -   
* Package-Analyze
  * Docker ✘  
  * Sonar ✔

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#938.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#938.1 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Pull request merged**
