### PR TITLE
fix(http): preserve BodyFile absolute path

### PR DESCRIPTION
**Pull request by fsamin**
Signed-off-by: François Samin <francois.samin@corp.ovh.com>

### CODE REVIEW

**Review by yesnault — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#1087.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#1092.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ivan-velasco** [comment]
I have tested this out and fails to work when we set `lib_dir` in `.venomrc` to root directory because the check done is for an absolute path. If the absolute path is set in configuration it works, but this would change per dev machine and testing envs. 
e.g. 
.venomrc
```yaml
lib_dir: lib
```
http.go
```go
if !filepath.IsAbs(e.BodyFile)
```

The test fails because no body is attached to the request.

I tested and suggest we change make two checks on the filepath to resolve this use case.
```go
if (!filepath.IsAbs(e.BodyFile)) && (!filepath.IsLocal(e.BodyFile)) {
```

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#15.0 ■   
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ■

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#15.0 ■   
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ■

**Pull request merged**
