### PR TITLE
chore: compute coverage

### PR DESCRIPTION
**Pull request by richardlt**
Signed-off-by: richardlt <richard.le.terrier@gmail.com>

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#575.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✔ 
* Analyse
  * Sonar ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#577.0 ■   
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ■

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#577.0 ■   
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ■

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#582.0 ■   
* Build
  * Build ■

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#582.0 ■   
* Build
  * Build ■

**Review by yesnault — APPROVED** [review]

**Review by fsamin — APPROVED** [review]

**Pull request merged**
