### PR TITLE
string interpolation

### PR DESCRIPTION
**Pull request by fokion**
I have noticed that we are not doing string  interpolation when we load the files during a test. Moreover when we do string interpolation it has to be recursive to the point that we dont have an unresolved variable. 
As a result I have created a PR to fix this issue.  Let me know your thoughts

### CODE REVIEW

**Comment by fokion** [comment]
@yesnault  is there an issue with the CI/CD pipeline ?

**Comment by fokion** [comment]
#657

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#14.0 ■   
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ■

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#14.0 ■   
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ■

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#34.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#38.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by yesnault** [comment]
thank you @fokion

**Pull request merged**
