### PR TITLE
feat(executor/kafka): Kafka Avro executor

### PR DESCRIPTION
**Pull request by fsamin**
- add a venom test for kafka venom tests

Signed-off-by: Fabrizio Moscon <mosconfabrizio@gmail.com>

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-venom#366.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom#367.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

**Review by yesnault — APPROVED** [review]

**Comment by fabriziomoscon** [comment]
@fsamin sorry, I left 1 reference to `kt` in the kafka test:
https://github.com/ovh/venom/commit/098a9c201eaa7808c2b4b2100e0898e47d561926#diff-458d52326c887c3f346ea7f0c5d51c8ec134f6b3b26e3d44843776be56b87bd3R35

it is actually not needed, because you restart the broker each time as part of your setup.

Would you also release version 0.29.0 packages? We would like to download a specific version

**Comment by fsamin** [comment]
No worry for that, i managed it with a small bash trick.
I think we will release 0.29.0 as a beta release in the next few days. There are a lot of changes and we have a bit of documentation to do before the 0.29.0 official release

**Comment by fabriziomoscon** [comment]
Thank you

**Pull request merged**
