### PR TITLE
Parse tests as HCL...

### PR DESCRIPTION
**Pull request by sean-**
This PR passes all tests.  I'd like it if someone at OVH could pull this branch down and run it through your paces locally to see if it breaks anything on your end.  I'm worried about one and only one change in this PR:

https://github.com/ovh/venom/commit/8bebffe2582d1f9e5623b3af950bb99eddb72b4c#diff-e871404fd69cab40521d6b2178847cf7R120

I think all of the decoders are doing the right thing, however, which is why that change was a nop and everything has continued to work as expected.  In particular I'm worried that the output of XML is somehow invalid or different. ?

### CODE REVIEW

**Comment by yesnault** [comment]
@sean- assertion on TestCase seems not used

**Comment by sean-** [comment]
@yesnault if that's the case, do you mind merging this? :grinning:

**Comment by yesnault** [comment]
@fsamin ok for you too ?

**Comment by fsamin** [comment]
👍

**Pull request merged**
