### PR TITLE
feat : perf improvement and many small features

### PR DESCRIPTION
**Pull request by yesnault**
Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

### CODE REVIEW

**Comment by yesnault** [comment]
fixed by https://github.com/ovh/venom/pull/160, withDetails does not exist anymore

**Comment by ovh-cds** [comment]
CDS Report build-venom#42.0 ✘  
* stage_0
  * Build ✔ 
  * Compile -  
* stage_1
  * Unit Test ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom#43.0 ✘  
* stage_0
  * Build ✔ 
  * Compile -  
* stage_1
  * Unit Test ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom#46.0 ✘  
* stage_0
  * Build ✘  
  * Unit Test ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom#46.1 ✘  
* stage_0
  * Build -  
  * Unit Test ✘

**Pull request merged**
