### PR TITLE
Improvements over kafka consumer executor

### PR DESCRIPTION
**Pull request by sixstone-qq**
:wave: again !

This is based on #394 to avoid conflicts so it may be better to read two last commmits.

Two minor improvements:

1. Introduce a mutex to share access to `messages` and `messagesJSON` between goroutines when more than 1 partition per topic is added.
2. Use `sarama.ConsumerGroupSession` context in `ConsumeClaim` for logging avoiding creating a new context when the parent one is already available.

Any review or feedback is more than welcome :hugs:

### CODE REVIEW

**Review by fsamin — APPROVED** [review]

**Review by yesnault — APPROVED** [review]

**Comment by yesnault** [comment]
@sixstone-qq Can you rebase this PR please ?

**Comment by sixstone-qq** [comment]
Done @yesnault !

**Comment by sixstone-qq** [comment]
Hey! Thanks a lot for merging these PRs @yesnault! do you foresee an upcoming release with these merged PR? :hugs:

**Comment by yesnault** [comment]
@sixstone-qq there is two issues, we will watch them before making a new release, hope this week

**Comment by sixstone-qq** [comment]
Let me know if I can help :hugs:

**Pull request merged**
