### PR TITLE
fix: godump formatter

### PR DESCRIPTION
**Pull request by yesnault**
this is a fix for the flapping integration test with tests/case.yml file.

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#81.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#106.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#109.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-venom-a#110.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

**Review by fsamin — APPROVED** [review]

**Pull request merged**
